import Head from 'next/head'

import { Inter } from 'next/font/google'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function Avartar(){
  return <Image
      src="/min.jpg"
      width={150}
      height={150}
      style={{ borderRadius: '50%', border: '2px solid black' }}
      alt="Picture of the author"
    />
}

function Section(){
  return <Image
      src="/min.jpg"
      width={150}
      height={150}
      style={{ borderRadius: '50%', border: '2px solid black' }}
      alt="Picture of the author"
    />
}

export default function Home() {
  const contactItems = ["Address", "Email", "Phone"]
  const mycontact = [["Nha Trang - Khanh Hoa"], ["nghia.vlm.62cntt@ntu.edu.vn"], ["0523053534"]]
  const myhobbies = ["Food", "Movie", "Travel", "Camping"]
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ backgroundColor: 'rgb(240, 240, 240)', maxWidth: '600px', margin: 'auto', borderRadius: '10px', border: '1px solidcc #c', padding: '20px' }}>
        <main style={{ display: 'flex', flexDirection: 'row', alignItems: 'center' }}>
        <div style={{ marginRight: '20px' }}>
          <Avartar/>
          {/* <Image
            src="/min.jpg"
            width={150}
            height={150}
            style={{ borderRadius: '50%', border: '2px solid black' }}
            alt="Picture of the author"
          /> */}
          <h3>Võ Lê Minh Nghĩa</h3>
        </div>
        <div>
          <div>  
            <h3>Contact</h3>
            <ul>
              {contactItems.map((item, index) => (
                <li key={index}>
                  <strong>{item}:</strong> {Array.isArray(mycontact[index]) ? (mycontact[index] as string[]).join(', ') : mycontact[index]}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h3>Department</h3>
            <ul>
              <li>Information Technology</li>
            </ul>
          </div>
        </div>
        <div style={{ marginTop: '-65px', marginLeft: '30px' }}> 
          <h3>Hobbies</h3>
          <ul>
            {myhobbies.map((hobby, index) => (
              <li key={index}>{hobby}</li>
            ))}
          </ul>
        </div>
      </main>
      </div>
    </>
  )
}

